### PR TITLE
Precise Time Reporting

### PR DESCRIPTION
**Pull request by uroybd**
Often, reporting precision to seconds doesn't show anything meaningful. This PR implements an option `-p` or `--precise` to allow the user to get the time precisely instead of a human-readable form.

### CODE REVIEW

**Comment by ctron** [comment]
Thanks for the PR. I think it might make sense to lift the `render` function into the `Processor`. In order to directly access the option through `self`.

**Comment by uroybd** [comment]
> Thanks for the PR. I think it might make sense to lift the `render` function into the `Processor`. In order to directly access the option through `self`.

I can do that. Should I?

**Comment by uroybd** [comment]
Do you mean the `readable` function?

We can also rename it to `format_duration`.

**Comment by ctron** [comment]
> Do you mean the `readable` function?
> 
> We can also rename it to `format_duration`.

+1 … I was only wondering if there was a way around passing the boolean option all the time.

**Review by ctron — APPROVED** [review]
LGTM, Thanks!

I can build a new release once merged. Or do you have some more changes?

**Comment by uroybd** [comment]
> LGTM, Thanks!
> 
> I can build a new release once merged. Or do you have some more changes?

Let's build. No more changes in my mind right now.

**Comment by ctron** [comment]
Released as 0.3.5, which a quick followup of 0.3.6, to fix a compiler warning due to a deprecated function in `chrono` that I missed before.

Thanks for the contribution!

**Comment by uroybd** [comment]
My pleasure!

**Pull request merged**
